### ISSUE TITLE
Incorporate good-sounds.org data

### ISSUE THREAD

**Issue by ejhumphrey** [ejhumphrey/minst-dataset#10]
http://mtg.upf.edu/download/datasets/good-sounds

> we are releasing the Good-sounds Dataset. It contains monophonic recordings of instrumental sounds and accompanying metadata. The dataset is composed by 8750 recordings of 12 different instruments (flute, cello, clarinet, trumpet, violin, alto sax, tenor sax, baritone sax, soprano sax, oboe, piccolo and double bass) recorded by 15 different musicians. Some of this recordings were performed using different microphones at the same time, leading to a total amount of 16308 audio files. Two kind of recordings are available: single notes of almost the whole range of each insturment as well as some scales.

**Comment by ejhumphrey** [comment]
@cjacoby just putting this on your radar

**Comment by cjacoby** [comment]
First pass of this in `feature/080616_add_goodsounds_dataset`

**Comment by cjacoby** [comment]
Completed with #21. :)
