### ISSUE TITLE
Regression tests for all in scripts

### ISSUE THREAD

**Issue by ejhumphrey** [ejhumphrey/minst-dataset#16]
- [x] scripts/collect_data.py
- [x] scripts/collect_onsets.py (what does this file do?)
- [x] scripts/split_audio_to_clips.py
- [x] scripts/compute_note_onsets.py

**Comment by ejhumphrey** [comment]
compute note onsets is checked end to end in `test_build`, but still warrants a more isolated test.

**Comment by cjacoby** [comment]
scripts/collect_onsets.py is for taking all your manually annotated
*_fix.csv's and moving/renaming them to their final location.
