### ISSUE TITLE
Makefile writes CSV index files to DATA_DIR

### ISSUE THREAD

**Issue by ejhumphrey** [ejhumphrey/minst-dataset#23]
Seems like this would be the preferred (expected) behavior. This fix _looks_ to be a little less than trivial, because of how dependencies are specified as file names.

Proposal:
- variables like `UIOWA_INDEX` only equal the file basename, e.g. `UIOWA_INDEX=uiowa_index`
- variables are escaped in the function calls, e.g. `$(PYTHON) scripts/collect_data.py uiowa $(UIOWA_DIR) $(DATA_DIR)/$(UIOWA_INDEX).csv --strict_taxonomy` 
- same goes for notes

will this work @cjacoby?

**Comment by cjacoby** [comment]
Um, no I think it would be better to do this:

```
UIOWA_DIR=$(DATA_DIR)/uiowa
PHIL_DIR=$(DATA_DIR)/philharmonia
RWC_DIR=$(DATA_DIR)/RWC\ Instruments
GOODSOUNDS_DIR=$(DATA_DIR)/good-sounds

UIOWA_INDEX=$(DATA_DIR)/uiowa_index.csv
PHIL_INDEX=$(DATA_DIR)/philharmonia_index.csv
RWC_INDEX=$(DATA_DIR)/rwc_index.csv
GOODSOUNDS_INDEX=$(DATA_DIR)/goodsounds_index.csv

UIOWA_NOTES=$(DATA_DIR)/uiowa_notes.csv
PHIL_NOTES=$(DATA_DIR)/phil_notes.csv
RWC_NOTES=$(DATA_DIR)/rwc_notes.csv
GOODSOUNDS_NOTES=$(DATA_DIR)/goodsounds_notes.csv
```

Then it will check the dependencies correctly.

**Comment by ejhumphrey** [comment]
Fixed in the `feature/cbj_20160824` branch
