### ISSUE TITLE
Generate "example dataset" with partitions in the same format as the canonical data.

### ISSUE THREAD

**Issue by cjacoby** [ejhumphrey/minst-dataset#34]
For "integration-testing" in Harmonic-CNN; need to have "example-dataset" (called tinyset in hcnn, but "example" here) set up in exactly the same format as the current output.

Modify `scripts/manage_dataset.py example` to output an example dataset, including:
* master_index.csv
* [test_set]_partitions.csv

Should be able to generate the example .csv and then call `train_test_split()` on it, I think.

Not incredibly blocking, but it would be nice to be able to clean up the code in HCNN to not have to handle both situations.

**Comment by ejhumphrey** [comment]
ya I think I can make quick work of this today. stay tuned.
