### ISSUE TITLE
clarify how to apply and use the provided onset annotations to build the actual dataset

### ISSUE THREAD

**Issue by faroit** [ejhumphrey/minst-dataset#5]
First, I really like the idea of this dataset and would find it very useful for my research. If you need some help I'm happy to provide some. :-)

As far as I understood the concept of this project this repo consists of:

1. scripts to download the raw audio data
2. scripts to segment the data by onset detection algorithms or user provided annotations
3. a python package inside of the `minst` folder which parses the cleaned up audio data and builds a dataset so that users can easily access the metadata and the corresponding audio files.

Since most users (like me) would just want to quickly build the dataset from the raw files (or idealy download the final dataset), I was looking for how to apply the user provided onset annotations. Maybe this could be described in the readme as well.

Then, afterwards, how would I then use the actual dataset? Also why are the onset detection methods part of this package and not part of the scripts to generate the clean dataset? I think this is a little bit confusing.

**Comment by faroit** [comment]
@cjacoby would love to try out the dataset... maybe it's just a one-liner... any help here?

**Comment by cjacoby** [comment]
@faroit - apologies; i went on vacation and have been generally swamped recovering from that. I'm working on it; the onset annotations are currently a little broken, but working on fixing them.

**Comment by ejhumphrey** [comment]
jumping in -- missed this entire thread :o(

**1. rundown on the project:** the numbered list is pretty close -- will def add it (or something comparable) to the readme, see (3) below.
**2. downloading:** I think the best we'll be able to do for a direct download is to share pre-computed features, e.g. librosa CQTs, like the MSD. this should help with RWC, and maybe even work for proprietary datasets, e.g. VSL, and other such things ... but IANAL.
**3. "how to use?":** The idea of this project is to go from raw, downloaded audio to instrument clips, like the MNIST handwritten number dataset (if the numbers were cropped from larger documents). Onset detectors are annoyingly imperfect, though, so we've gone back through and manually cleaned up that mess.
**4. help:** as you can tell from the epic response delay, we are woefully swamped. any and all help would be amazing. I'm increasingly leaning toward trying to rally a crew around HAMR@ISMIR2016 to get this thing in a much better place in the next few days. if you're coming (or want to hack along remotely), let me know.

**Comment by ejhumphrey** [comment]
@faroit this project's in a much better (developed and documented) state than at the time of your original ping ... unless you have any other feedback, I'm going to close this issue.

**Comment by faroit** [comment]
@ejhumphrey that sounds great. I am currently on vacation an will get back to be project in september. Also: I'd still love to contribute. So I will add more feedback later here (in separate issues) once I've managed to build the dataset.
